### ISSUE TITLE
Lua errors

### ISSUE THREAD

**Issue by KekkyShmekky** [Rynoxx/gmod-addon-collection#4]
I am  
- [* ] Reporting a bug  
- [ ] Giving a suggestion  

---
If you're reporting a bug, please answer the following questions (if not, this section can be removed):  
Are there any lua errors? If so, include them below.  

`[ERROR] lua/weapons/gmod_tool/stools/transfer_ownership.lua:226: bad argument #1 to 'Player' (number expected, got string)
  1. Player - [C]:-1
   2. RightClick - lua/weapons/gmod_tool/stools/transfer_ownership.lua:226
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:266
    
    [ERROR] lua/weapons/gmod_tool/stools/transfer_ownership.lua:199: bad argument #1 to 'Player' (number expected, got string)
  1. Player - [C]:-1
   2. LeftClick - lua/weapons/gmod_tool/stools/transfer_ownership.lua:199
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:236`

What is the desired behaviour? And what is the current behaviour?

So I noticed this happens when a player isn't selected, while it should either automatically select the first player in the list by default or print a text message indicating a player needs to be selected first. The current behaviour is that it produces Lua errors before the player figures out that they need to select a player in the Q-menu.

How do you reproduce the issue?  

Try to use this tool without setting a player first.

If you're giving a suggestion, please be as descriptive as possible! :smile:

**Comment by Rynoxx** [comment]
Workshop has now been updated with latest version
